# Host
:host = http://localhost:3332

:langCode = NL

# Search zip code id
:query = 3000
GET :host/api/search-zipcode?q=:query&lang_code=:langCode

# Zip code id
:zipcodeId = 3000-24062

# Search street id
:query = Grote
GET :host/api/search-street?zipcode=:zipcodeId&q=:query&lang_code=:langCode

# Street id
:streetId = https://data.vlaanderen.be/id/straatnaam-34867

# House number
:houseNumber = 1

# Todo encoding configuration
:todoDueDaysBefore = 5
:todoDueTime = 20:00
# :todoDueType = date&tdb=:todoDueDaysBefore
:todoDueType = datetime&tdb=:todoDueDaysBefore&tt=:todoDueTime

# Event encoding configuration
# :fractionEncoding = todo&tdt=:todoDueType
:eventStart = 08:00
:eventEnd = 10:00
:reminders = rdb=0&rt=07:00&rdb=1&rt=23:00&rdb=1&rt=20:00

# Fraction encoding
:fractionEncoding = event&es=:eventStart&ee=:eventEnd&:reminders

# Date range
:dateRangeType = absolute
:fromDate = 2021-11-18
:untilDate = 2021-11-19

# Filter
:filter = &fl=e

# Generate ICS file for absolute date range
GET :host/api/generate?drt=:dateRangeType&f=:fromDate&t=:untilDate&z=:zipcodeId&s=:streetId&hn=:houseNumber&lc=:langCode&fe=:fractionEncoding:filter
