# Host
:host = https://api.fostplus.be
# BaseUrl
:baseUrl = :host/recycle-public/app/v1

# Consumer
:consumer = recycleapp.be
# Secret
:secret = <REDACTED>

# Get access token
GET :baseUrl/access-token
X-Consumer: :consumer
X-Secret: :secret

# Access token
:accessToken = <REDACTED>

# Search zip code id
:query = 3000
GET :baseUrl/zipcodes?q=:query
X-Consumer: :consumer
Authorization: :accessToken

# Zip code id
:zipCodeId = 3000-24062

# Search street id
:query = Andreas
POST :baseUrl/streets?q=:query&zipcodes=:zipCodeId
X-Consumer: :consumer
Authorization: :accessToken

# Street id
:streetId = https://data.vlaanderen.be/id/straatnaam-34637

# Request calendar
:houseNumber = 73
:fromDate = 2021-09-15
:untilDate = 2021-12-14
:size = 200
GET :baseUrl/collections?zipcodeId=:zipCodeId&streetId=:streetId&houseNumber=:houseNumber&fromDate=:fromDate&untilDate=:untilDate
Authorization: :accessToken
X-Consumer: :consumer

# Fractions
GET :baseUrl/fractions?zipcodeId=:zipCodeId&streetId=:streetId&houseNumber=:houseNumber
Authorization: :accessToken
X-Consumer: :consumer